import { prisma } from './config/prisma.js';
import { Prisma } from './generated/prisma/client.js';

const seedDB = async () => {
  try {
    await prisma.product.deleteMany({});
    console.log('Cleared existing products');
    const products: Prisma.ProductCreateManyInput[] = [
      {
        name: 'Масляный круассан 100г',
        description: 'Слоёный и маслянистый',
        price: 90,
        originalPrice: 100,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/zvoeqbvrbrt7atqj0dbu.png',
        category: 'bakery',
        unit: '100g',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Органическая киноа 500г',
        description: 'Высокое содержание белка, без глютена',
        price: 840,
        originalPrice: 900,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/cxrrgnf12xuhkr4dyhi2.png',
        category: 'pantry-staples',
        unit: '500g',
        stock: 100,
        isOrganic: true,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Цельнозерновой хлеб 400г',
        description: 'Мягкий и полезный, идеален для завтрака',
        price: 70,
        originalPrice: 80,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/vy1xa7zovcu22smzapzv.png',
        category: 'bakery',
        unit: '400g',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Ячмень 1кг',
        description: 'Богат клетчаткой, улучшает пищеварение',
        price: 280,
        originalPrice: 300,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/spb5sgy8g24rned9nwog.png',
        category: 'pantry-staples',
        unit: '1kg',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Суп Knorr в чашке 70г',
        description: 'Удобно и вкусно',
        price: 60,
        originalPrice: 70,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/vnzb2qbwtpab5gnqvx0f.png',
        category: 'pantry-staples',
        unit: '70g',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Лапша Maggi 280г',
        description: 'Быстро и легко готовится',
        price: 100,
        originalPrice: 110,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/dsep7owmwvfrukzbslqo.png',
        category: 'pantry-staples',
        unit: '280g',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Спрайт 1.5л',
        description: 'Охлаждённый и освежающий, идеален для праздников',
        price: 120,
        originalPrice: 150,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/daiglpvgna1dlhjplbve.png',
        category: 'beverages',
        unit: '1.5L',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Морковь 500г',
        description: 'Сладкая и хрустящая, полезна для зрения, идеальна для соков и салатов',
        price: 88,
        originalPrice: 100,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/ceqgisupuizyste9aifg.png',
        category: 'fruits-vegetables',
        unit: '500g',
        stock: 100,
        isOrganic: true,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Кока-Кола 1.5л',
        description: 'Идеально для вечеринок, лучше подавать охлаждённым',
        price: 150,
        originalPrice: 160,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/eljxcdud6fduwfim5rdx.png',
        category: 'beverages',
        unit: '1.5L',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Бурый рис 1кг',
        description: 'Цельнозерновой и питательный',
        price: 220,
        originalPrice: 240,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/dboutcrkdjhoxcvbbqne.png',
        category: 'pantry-staples',
        unit: '1kg',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Яйца 12 шт',
        description: 'Свежие с фермы, богаты белком, идеальны для завтрака и выпечки',
        price: 170,
        originalPrice: 180,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/cnjrpbcnqesqxy1wr30g.png',
        category: 'dairy-eggs',
        unit: '12pcs',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Бананы 1 кг',
        description: 'Сладкие и спелые, богаты калием, отлично для смузи и перекуса',
        price: 90,
        originalPrice: 100,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/dsnmko6gqtyw31okby80.png',
        category: 'fruits-vegetables',
        unit: '1kg',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Рис Басмати 5кг',
        description: 'Длиннозёрный и ароматный, идеален для плова',
        price: 1040,
        originalPrice: 1100,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/evuovl2nlwdjukosfz23.png',
        category: 'pantry-staples',
        unit: '5kg',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Лук 500г',
        description: 'Свежий и острый, идеален для готовки, незаменим на кухне',
        price: 90,
        originalPrice: 100,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/wnvtwlm2tphqburhsmyc.png',
        category: 'fruits-vegetables',
        unit: '500g',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: '7 Up 1.5л',
        description: 'Освежающий вкус лимона и лайма',
        price: 140,
        originalPrice: 152,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/qt1ypzsoqni12ghf2ryp.png',
        category: 'beverages',
        unit: '1.5L',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Шпинат 500г',
        description: 'Богат железом и витаминами, идеален для супов и салатов',
        price: 30,
        originalPrice: 36,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/bhrtl76sscvmeiq4kchm.png',
        category: 'fruits-vegetables',
        unit: '500g',
        stock: 100,
        isOrganic: true,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Апельсины 1 кг',
        description: 'Сочные и сладкие, богаты витамином C, идеальны для соков и салатов',
        price: 150,
        originalPrice: 160,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/r1wxfortw5h12g7egx7k.png',
        category: 'fruits-vegetables',
        unit: '1kg',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Пшеничная мука 5кг',
        description: 'Мягкие и пышные лепёшки, богата питательными веществами',
        price: 460,
        originalPrice: 500,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/ooitbkcjcky0gkjmkatb.png',
        category: 'pantry-staples',
        unit: '5kg',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Виноград 500г',
        description: 'Свежий и сочный, богат антиоксидантами, идеален для перекуса и фруктовых салатов',
        price: 130,
        originalPrice: 140,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/jsmb7caaokhnyci2coga.png',
        category: 'fruits-vegetables',
        unit: '500g',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Фанта 1.5л',
        description: 'Сладкая и газированная',
        price: 130,
        originalPrice: 140,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/nexecd3mgyzrpeun1bee.png',
        category: 'beverages',
        unit: '1.5L',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Панир 200г',
        description: 'Мягкий и свежий, богат белком, идеален для карри и закусок',
        price: 170,
        originalPrice: 180,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/vihqr6wquv57byurvz46.png',
        category: 'dairy-eggs',
        unit: '200g',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Манго 1 кг',
        description: 'Сладкое и ароматное, идеально для смузи и десертов, богато витамином A',
        price: 280,
        originalPrice: 300,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/nb1mpxuo4fdcik6ey5yj.png',
        category: 'fruits-vegetables',
        unit: '1kg',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Помидоры 1 кг',
        description: 'Сочные и спелые, богаты витамином C, идеальны для салатов и соусов, свежие с фермы',
        price: 56,
        originalPrice: 60,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/kdbfytxisrjymgy0ubhk.png',
        category: 'fruits-vegetables',
        unit: '1kg',
        stock: 100,
        isOrganic: true,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Картофель 500г',
        description: 'Свежий и органический, богат углеводами, идеален для карри и жарки',
        price: 70,
        originalPrice: 80,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/tzibj2ntsnbn4e0u5kwv.png',
        category: 'fruits-vegetables',
        unit: '500g',
        stock: 100,
        isOrganic: true,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Сыр 200г',
        description: 'Сливочный и вкусный, идеален для пиццы и сэндвичей, богат кальцием',
        price: 260,
        originalPrice: 280,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/gek3mmiig3lixlkpxks8.png',
        category: 'dairy-eggs',
        unit: '200g',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Молоко Amul 1л',
        description: 'Свежее молоко, богато кальцием',
        price: 110,
        originalPrice: 120,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/ooamzy497lhsj2gjuwby.png',
        category: 'dairy-eggs',
        unit: '1L',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
      {
        name: 'Яблоки 1 кг',
        description: 'Укрепляет иммунитет, богато клетчаткой',
        price: 180,
        originalPrice: 200,
        image: 'https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/pjt1y6xdo46tluemhf0o.png',
        category: 'fruits-vegetables',
        unit: '1kg',
        stock: 100,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 12,
      },
    ];
    await prisma.product.createMany({data: products})
    console.log(`Created ${products.length} products`)
    console.log(`Seed completed successfully`)
    process.exit(0)
  } catch (error) {
    console.log("Seed error:", error)
    process.exit(1)
  } finally{
    await prisma.$disconnect
  }
};

seedDB()